# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bid', models.FloatField(blank=True)),
                ('bid_type', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('bid_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CPC', 'CPC'), ('CPM', 'CPM'), ('CPA', 'CPA'), ('CPV', 'CPV'), ('CPI', 'CPI')], default='CPM', max_length=3), size=None)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids_app.Channel'),
        ),
    ]
